language: python
python:
  - 2.6
  - 2.7
install:
  # 12.04 LTS ships an outdated texlive https://launchpad.net/bugs/712521
  - sudo add-apt-repository --yes ppa:texlive-backports/ppa
  - sudo apt-get update -yq2
  - sudo apt-get install -yq2 --no-install-recommends dvipng graphviz imagemagick lilypond source-highlight texlive-latex-base
script:
  - time python tests/testasciidoc.py update
  - python asciidoc.py --doctest
  - python asciidocapi.py
  - time python tests/testasciidoc.py run
  - git clean -x -f doc tests/data
